---
uyuni_repo_file: /etc/yum.repos.d/susemanager:channels.repo

client_packages:
  - venv-salt-minion
uyuni_minion_service: venv-salt-minion
client_directories:
  - /etc/venv-salt-minion
  - /var/cache/venv-salt-minion
