---
- name: Ensure having 15 SP4 release
  fail: msg="Please ensure having SP4"
  when:
    - "ansible_distribution_version != '15.4'"
    - "uyuni_release is version('2022.06', '>=')"

- name: Ensure having 15 SP3 release
  fail: msg="Please ensure having SP3"
  when:
    - "ansible_distribution_version != '15.3'"
    - "uyuni_release is version('2021.06', '>=')"
    - "uyuni_release is version('2022.06', '<')"

- name: Ensure having 15 SP2 release
  fail: msg="Please ensure having SP2"
  when:
    - "ansible_distribution_version != '15.2'"
    - "uyuni_release is version('2020.07', '>=')"
    - "uyuni_release is version('2021.06', '<')"

- name: Ensure that Uyuni is already installed
  command: "rpm -qpi {{ uyuni_pattern }}"
  register: rpm
  failed_when: rpm.rc != 0
