---
- name: Check system registration
  ansible.builtin.command: SUSEConnect --status
  changed_when: false
  register: scc_registration
  when: uyuni_scc_check_registration or uyuni_scc_check_modules
  become: true

- name: Register system
  ansible.builtin.command: "suseconnect --url {{ uyuni_scc_url }} -p SUSE-Manager-Server/{{ uyuni_suma_release }}/{{ ansible_architecture }} -r {{ item }} -e {{ uyuni_scc_mail }}"
  when:
    - uyuni_scc_check_registration
    - 'scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    query_filter: "[?identifier == 'SUSE-Manager-Server'].status"
  loop: "{{ uyuni_scc_reg_code }}"
  become: true

- name: Enable modules
  ansible.builtin.command: "suseconnect --url {{ uyuni_scc_url }} -p {{ item.identifier }}"
  loop: "{{ uyuni_slm_modules }}"
  when:
    - uyuni_scc_check_modules
    - 'scc_registration.stdout | from_json | json_query(query_filter) | join | lower != "registered"'
  vars:
    query_filter: "[?identifier == '{{ item.name }}'].status"
  become: true

- name: Set default image name
  ansible.builtin.set_fact:
    uyuni_image_name: registry.suse.com/suse/manager/5.0/{{ ansible_architecture }}/server
  when: uyuni_suma_release is not defined

- name: Set default image name (release-specific)
  ansible.builtin.set_fact:
    uyuni_image_name: registry.suse.com/suse/manager/{{ uyuni_suma_release }}/{{ ansible_architecture }}/server
  when: uyuni_suma_release is defined
